### ISSUE TITLE
Importing .gpx/.xml is very slow

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#40] opened 2015-11-08 20:07 UTC
There are two places:
- whole document is read into the memory,
- converting profile into internal format.

Event-driven parsing (SAX) should be much faster. Memory allocation (especially for big files) takes a lot of time.

-- EDIT
Reading documents is not a big issue. My biggest .xml takes up to 10s. It is not proper RLV file, of course.. This time shall be "spent"/"spoled" during importing on purpose.

About "conversion".. My biggest .gpx (35M, some 30 hours of ride) is read in 3s. The issue is parsing: it takes about 80s! No one will bother it (every start!).
I've got prepared video for shorter route (10h), but 30s is annoying as well..
I've started thinking about "lazy reading" already imported files..

**Comment by ibooij** [comment] 2015-11-09 08:20
The problem is probably not Qt's XML parser itself. That is a QXmlStreamReader, which is a pull-based stream parser. We should do some profiling to see where in the code the biggest slowdown occurs.

**Comment by ibooij** [comment] 2015-11-25 20:14
This fix is now on the develop branch. Will land in master after some testing. As I'm not home this week, I won't be able to really done any real-life testing. Hopefully this weekend.

**Comment by ibooij** [comment] 2015-11-25 20:16
By the way, the fix is done by caching the contents of rlv files. Just store the content of the RealLifeVideo class to a binary file, using QDataStream. When loading, just use the QDataStream to load the RealLifeVideo object back. Simple. Of course, there is check to see if the original file might be newer than the cache file. In that case the original is read.

This cuts back parsing on some of my files from about 1500ms to 10ms. Quite a gain.

**Comment by pajakgdynia** [comment] 2015-11-25 21:42
So.. my "internal format" is back again. Anyway, I haven't thought about just streaming the object, and indeed it seems to be the best method :)
The only question is.. If all additional data were in this file (I mean custom courses, POIs, segments, timechecks, results..).. What about merging "streamed" with the "original" file? Or should all settings be kept in config, and not streamed at all?
My another idea is.. Importing might be done on request. If there is a conflict, either data is merged, or discarded (or new route is created). Changed routes would have a warning sign to indicate modified routes..

**Comment by pajakgdynia** [comment] 2015-11-25 21:56
I've seen you're fast! So keeping files in "cache" makes my idea ("additional" data in config) somehow obsolete. Could you take a look at my "import_videos" branch?

**Comment by ibooij** [comment] 2015-12-09 12:19
Caching of ride files has been merged into maste in 4e056157c8534f6f4a8f8bb8eebac4b2e987df83

**Closed by ibooij** 2015-12-09 12:19 UTC
